### ISSUE TITLE
 get and retain individuals ID an plate links (improvement point)

### ISSUE THREAD

**Issue by hmkim** [nicolazzie/AffyPipe#3]
for i in range(len(tut)):
    print tut[i]
...
5505744243493031116990_A01
5505744243493031116990_A02
5505744243493031116990_A03
5505744243493031116990_A04
5505744243493031116990_A05
5505744243493031116990_A06
5505744243493031116990_A07
5505744243493031116990_A08
5505744243493031116990_A09
5505744243493031116990_A10
5505744243493031116990_E4
5505744243493031116990_E5
5505744243493031116990_E6
5505744243493031116990_E7
...

If you have the cel filename like name in upper,
AffyPipe can't get the plate correctly.

Again, 5505744243493031116990_A10 and 5505744243493031116990_E4 are belong to same plate. but, Affypipe divde the plateID.

[AffyPipe.py]
    else:             ## IF default behavior, get and retain individuals ID an plate links
        temp=[tut[i][:-4] for i in range(len(tut))]
        for en,i in enumerate(tut):animplate[i]=temp[en]
        plates=[(i,temp.count(i)) for i in set(temp)]
=>
    else:             ## IF default behavior, get and retain individuals ID an plate links
        temp=[tut[i].split('_')[0] for i in range(len(tut))]
        for en,i in enumerate(tut):animplate[i]=temp[en]
        plates=[(i,temp.count(i)) for i in set(temp)]

I am not certain this manner. In my situation this manner is needed.

**Comment by nicolazzie** [comment]
Dear Hmkim,
There's a default behaviour, which identifies the ids based on the initial part of the names (default for buffalo data, at least in most cases), and a way to modify the default behaviour, which is by specifying a platefile, containing that specific information (see -f or --platefile option). 
I don't see the point of changing the default behaviour, although it could be a good idea actually erasing A default behaviour when "bestpractice" option is active... in this way everybody will have to create a plate file.
Thank you for your continuous ideas, please be aware of the big WARNING sign I put yesterday on the main page concerning a bug in the --plink and --plinkACGT options (you should download the most recent version!!!)

Best regards,
Ezequiel

**Comment by hmkim** [comment]
yes I checked it before. There are genotype issue.
so, I handled this issue in my hands. 

Thanks.
