### ISSUE TITLE
Question for genotype

### ISSUE THREAD

**Issue by hmkim** [nicolazzie/AffyPipe#5]
Hi, nicolazzie

I review your code and I found the {geno_code} is no changed when user no have PLINKacgt.

660>    geno_code = {'0':'B B', '1':'A B', '2':'A A', '-1':'0 0'}

check your 660 line (https://github.com/nicolazzie/AffyPipe/blob/master/AffyPipe.py)

and check your message code.

701>     logit('Genotypes were recoded as follows: 0="B/B", 1="A/B" and 2="A/A" -1="0/0"')

Am I mistake?

Thanks,
Hyunmin

**Comment by nicolazzie** [comment]
No mistake @hmkim , thanks for that (again!). I've uploaded the patch for that.... I hate when this happens! :)

Best,
Ezequiel

**Comment by hmkim** [comment]
Thanks!

Best regards,
Hyunmin
